config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'sessions/new'
  get 'sections/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "pages#show", :id => 4
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :pages, :users, :statutes, :resources, :sections

end

app/models/section.rb
class Section < ApplicationRecord
    
    def to_param
        "#{id} INA #{ina} #{fullcite}".parameterize
    end
    
    def next
        self.class.where("id > ?", id).first
    end

    def previous
        self.class.where("id < ?", id).last
    end
    
    def self.search(search)
        where("content LIKE ?", "%#{search}%").order('id ASC')
    end
    
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :logged_in_user, only: [:new, :edit, :update, :destroy]
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.search(params[:search]).paginate(page: params[:page], per_page: 25)
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    
  end

  def self.search(term)
    @sections = Section.search(params[:term])
    if term
      where('content LIKE ?', "%#{term}%").order('id ASC')
    else
      order('id ASC') 
    end
  end
  
  # GET /sections/new
  def new
    @section = Section.new
  end
  
  def search_params
    params.require(:content).permit(:name, :complete, :due_date, :term)
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:citation, :section, :level, :ina, :usc, :content)
    end
    
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/helpers/sections_helper.rb
module SectionsHelper

end

app/views/sections/_form.html.erb
<%= form_for(section) do |f| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :citation %>
    <%= f.text_field :citation %>
  </div>

  <div class="field">
    <%= f.label :section %>
    <%= f.number_field :section %>
  </div>

  <div class="field">
    <%= f.label :level %>
    <%= f.number_field :level %>
  </div>

  <div class="field">
    <%= f.label :ina %>
    <%= f.text_field :ina %>
  </div>

  <div class="field">
    <%= f.label :usc %>
    <%= f.text_field :usc %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.slim
h1 Editing Section
= render 'form', section: @section
= link_to 'Show', @section
| \
= link_to 'Back', sections_path

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>
<%= will_paginate @sections %>
<table>
  <thead>
    <tr>
      <th>Citation</th>
      <th>Section</th>
      <th>Level</th>
      <th>Ina</th>
      <th>Usc</th>
      <th>Content</th>
      <th>Fullcite</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.citation %></td>
        <td><%= section.section %></td>
        <td><%= section.level %></td>
        <td><%= section.ina %></td>
        <td><%= section.usc %></td>
        <td><%= section.content %></td>
        <td><%= section.fullcite %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @sections %>
<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/index.html.haml
%p#notice= notice
%h1 Sections
= will_paginate @sections
%table
  %thead
    %tr
      %th Citation
      %th Section
      %th Level
      %th Ina
      %th Usc
      %th Content
      %th Fullcite
      %th{:colspan => "3"}
  %tbody
    - @sections.each do |section|
      %tr
        %td= section.citation
        %td= section.section
        %td= section.level
        %td= section.ina
        %td= section.usc
        %td= section.content
        %td= section.fullcite
        %td= link_to 'Show', section
        %td= link_to 'Edit', edit_section_path(section)
        %td= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' }
= will_paginate @sections
%br/
= link_to 'New Section', new_section_path

app/views/sections/index.html.slim
p#notice= notice
h1 Sections
= will_paginate @sections
table
  thead
    tr
      th Citation
      th Section
      th Level
      th Ina
      th Usc
      th Content
      th Fullcite
      th colspan="3" 
  tbody
    - @sections.each do |section|
      tr
        td= section.citation
        td= section.section
        td= section.level
        td= section.ina
        td= section.usc
        td= section.content
        td= section.fullcite
        td= link_to 'Show', section
        td= link_to 'Edit', edit_section_path(section)
        td= link_to 'Destroy', section, method: :delete, data:   confirm: 'Are you sure?'  
= will_paginate @sections
br/
= link_to 'New Section', new_section_path

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

app/views/sections/new.html.haml
%h1 New Section
= render 'form', section: @section
= link_to 'Back', sections_path

app/views/sections/new.html.slim
h1 New Section
= render 'form', section: @section
= link_to 'Back', sections_path

app/views/sections/search.html.erb
<h1>Search the INA</h1>
<p id="notice"><%= notice %></p>

<%= form_tag(sections_path, method: :get) do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>

app/views/sections/search.html.haml
%h1 Search the INA
%p#notice= notice
= form_tag(sections_path, method: :get) do
  = text_field_tag :search, params[:search]
  = submit_tag 'Search', name: nil

app/views/sections/search.html.slim
h1 Search the INA
p#notice= notice
= form_tag(sections_path, method: :get) do
  = text_field_tag :search, params[:search]
  = submit_tag 'Search', name: nil

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  INA <%= @section.ina %><%= @section.fullcite %>: <%= @section.content %>
</p>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.haml
%p#notice= notice
%p
  INA #{@section.ina}#{@section.fullcite}: #{@section.content}
= link_to 'Back', sections_path

app/views/sections/show.html.slim
p#notice= notice
p
  | INA #{@section.ina}#{@section.fullcite}: #{@section.content}
= link_to 'Back', sections_path