config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'sessions/new'
  get 'sections/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "pages#show", :id => 4
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :pages, :users, :statutes, :resources, :sections

end

app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.trix_editor :content %>
    
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/edit.html.haml
%h1 Editing Page
= render 'form', page: @page
= link_to 'Show', @page
|
= link_to 'Back', pages_path

app/views/pages/home.html.erb
<h1>Immigration and Nationality Act</h1>


<table>
  <thead>
    <tr>
      <th>Ina</th>
      <th>Usc</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statutes.each do |statute| %>
      <tr>
        <td><%= statute.ina %></td>
        <td><%= statute.usc %></td>
        <td><%= link_to statute.title, statute %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/home.html.haml
%h1 Immigration and Nationality Act
%table
  %thead
    %tr
      %th Ina
      %th Usc
      %th Title
      %th{:colspan => "3"}
  %tbody
    - @statutes.each do |statute|
      %tr
        %td= statute.ina
        %td= statute.usc
        %td= link_to statute.title, statute

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%=raw page.content %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <%= value %>
      </div>
<% end %>

<h1><%=raw @page.title %></h1>

<p><%=raw @page.content %></p>

<% if logged_in? %><%= link_to 'Edit', edit_page_path(@page) %><% end %>