config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'sessions/new'
  get 'sections/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "pages#show", :id => 4
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :pages, :users, :statutes, :resources, :sections

end

app/views/resources/_form.html.erb
<%= form_for(resource) do |f| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.trix_editor :content %>
  </div>

  <div class="field">
    <%= f.label :original %>
    <%= f.text_field :original %>
  </div>

  <div class="field">
    <%= f.label :file %>
	  <%= f.file_field :file  %>
	</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/_form.html.haml
= form_for(resource) do |f|
  - if resource.errors.any?
    #error_explanation
      %h2
        = pluralize(resource.errors.count, "error")
        prohibited this resource from being saved:
      %ul
        - resource.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.trix_editor :content
  .field
    = f.label :original
    = f.text_field :original
  .field
    = f.label :file
    = f.file_field :file
  .actions
    = f.submit

app/views/resources/_form.html.slim
= form_for(resource) do |f|
  - if resource.errors.any?
    #error_explanation
      h2
        = pluralize(resource.errors.count, "error")
        | prohibited this resource from being saved:
      ul
        - resource.errors.full_messages.each do |message|
          li= message
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.trix_editor :content
  .field
    = f.label :original
    = f.text_field :original
  .field
    = f.label :file
    = f.file_field :file
  .actions
    = f.submit

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/edit.html.haml
%h1 Editing Resource
= render 'form', resource: @resource
= link_to 'Show', @resource
|
= link_to 'Back', resources_path

app/views/resources/edit.html.slim
h1 Editing Resource
= render 'form', resource: @resource
= link_to 'Show', @resource
| \
= link_to 'Back', resources_path

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resources</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Original</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.title %></td>
        <td><%= resource.original %></td>
        <td><a href="<%= resource.url %>">Download</a></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/index.html.haml
%p#notice= notice
%h1 Resources
%table
  %thead
    %tr
      %th Title
      %th Original
      %th Url
      %th{:colspan => "3"}
  %tbody
    - @resources.each do |resource|
      %tr
        %td= resource.title
        %td= resource.original
        %td
          %a{:href => "#{resource.url}"} Download
        %td= link_to 'Show', resource
        %td= link_to 'Edit', edit_resource_path(resource)
        %td= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Resource', new_resource_path

app/views/resources/index.html.slim
p#notice= notice
h1 Resources
table
  thead
    tr
      th Title
      th Original
      th Url
      th colspan="3" 
  tbody
    - @resources.each do |resource|
      tr
        td= resource.title
        td= resource.original
        td
          a href="#{resource.url}"  Download
        td= link_to 'Show', resource
        td= link_to 'Edit', edit_resource_path(resource)
        td= link_to 'Destroy', resource, method: :delete, data:   confirm: 'Are you sure?'  
br/
= link_to 'New Resource', new_resource_path

app/views/resources/new.html.haml
%h1 New Resource
= render 'form', resource: @resource
= link_to 'Back', resources_path

app/views/resources/new.html.slim
h1 New Resource
= render 'form', resource: @resource
= link_to 'Back', resources_path

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @resource.title %></h2>

<p><%=raw @resource.content %></p>

<p>Source: <%= @resource.original %></p>

<p>Download: <a href="<%= @resource.url %>"><%= @resource.title %></a></p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/resources/show.html.haml
%p#notice= notice
%h1
  = @resource.title
%p= raw @resource.content
%p
  Source: #{@resource.original}
%p
  Download:
  %a{:href => "#{@resource.url}"}= @resource.title
= link_to 'Edit', edit_resource_path(@resource)
|
= link_to 'Back', resources_path

app/views/resources/show.html.slim
p#notice= notice
h1
  = @resource.title
p= raw @resource.content
p
  | Source: #{@resource.original}
p
  | Download:
  a href="#{@resource.url}" = @resource.title
= link_to 'Edit', edit_resource_path(@resource)
| \
= link_to 'Back', resources_path