config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'sessions/new'
  get 'sections/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "pages#show", :id => 4
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :pages, :users, :statutes, :resources, :sections

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- this is already not necessary -->
  <!-- <link rel="stylesheet" type="text/css" href="/assets/trix.css">
  <script type="text/javascript" src="/assets/trix.js"></script> -->
  <!-- this is already not necessary -->

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
  <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <%= link_to "Immigrant and Refugee Center", root_path, class: "navbar-brand" %>

    <ul class="nav navbar-nav float-xs-right">
      <li class="nav-item"><%= link_to "Home",   root_path, { :class=>"nav-link" } %></li>
      <li class="nav-item"><%= link_to "INA",   statutes_path, { :class=>"nav-link" } %></li>
      <% if logged_in? %>
      <li class="nav-item"><%= link_to "Pages", pages_path, { :class=>"nav-link" } %></li>
      <li class="nav-item"><%= link_to "Upload", resources_path, { :class=>"nav-link" } %></li>
      <li class="nav-item">
        <%= link_to "Log out", logout_path, {method: "delete", class: "nav-link" }  %>
      </li>
      <% else %>
      <li class="nav-item"><%= link_to "Log in", '/login', { :class=>"nav-link" } %></li>
      <% end %>
    </ul>
  </nav>
  
  <div class="container-fluid">

    <%= yield %>
  </div>
</body>
</html>